### ISSUE TITLE
Deign guidelines

### ISSUE THREAD

**Issue by Bolling88** [bazookon/giphy_get#13]
Currently, to be able to get a production key, one needs to add the "Powered by Giphy" icon and add shortcut to each giphys creator, as according to this:
https://developers.giphy.com/docs/sdk/#data-collection

Is this work in the pipeline?

**Comment by KhalidScrypt** [comment]
Anyone still maintaining this plugin? Seems like an easy change... Would like to clone this but won't have time to maintain it :(

**Comment by bazookon** [comment]
@KhalidScrypt yes, do you have some pull request?

**Comment by bazookon** [comment]
hey @Bolling88 can yout test this [verision](https://pub.dev/packages/giphy_get/versions/3.0.0-pre.1), please

**Comment by bazookon** [comment]
fixed in v3.0.1

**Comment by bazookon** [comment]
close
