### ISSUE TITLE
Width calculation only is correct when the view takes up the whole width of the screen.

### ISSUE THREAD

**Issue by m-j-g** [bazookon/giphy_get#19]
Nice work on the bottom modal.  
There is an issue with the width calculation anytime the view doesn't take up the full screen  (landscape tablets or web implementations).   line 91 in giphy_tab_detail.dart is using (MediaQuery.of(context).size.width which is simply the width of the screen and not the width of the view.  Using a LayoutBuilder to get the constraints maxwidth would fix this issue.  

<img width="575" alt="Screen Shot 2022-01-20 at 8 13 47 AM" src="https://user-images.githubusercontent.com/10711395/150355101-c6c58aae-dba4-460a-83d4-7f55276e6523.png">

**Comment by bazookon** [comment]
thank's, can you make a pull request fixing this issue?

**Comment by bazookon** [comment]
hello @m-j-g can you test this [version](https://pub.dev/packages/giphy_get/versions/3.0.0-pre.1) if this issue has fixed?

**Comment by bazookon** [comment]
fixed in version 3.0.1
