### ISSUE TITLE
Gif and sticker is fine but emoji is not working for me

### ISSUE THREAD

**Issue by kiburtemesgen** [bazookon/giphy_get#23]
![image](https://user-images.githubusercontent.com/92824995/152734038-fbfd5df9-9e4b-4b15-8ff6-4f8193396706.png)

**Comment by kiburtemesgen** [comment]
I fixed the issue by replacing collection.dart of  giphy_get with collection.dart from giphy_picker pluging and works fine.

**Comment by bazookon** [comment]
thanks!
