### ISSUE TITLE
null-aware operation Warnings

### ISSUE THREAD

**Issue by mashegoindustries** [bazookon/giphy_get#27]
I just upgraded to latest version and I am suddenly getting the warnings below

../../../../.pub-cache/hosted/pub.dartlang.org/giphy_get-3.0.4/lib/src/views/tab/giphy_tab_detail.dart:238:22: Warning: Operand of null-aware operation '!' has type 'List<GiphyGif>' which excludes null.
 - 'List' is from 'dart:core'.
 - 'GiphyGif' is from 'package:giphy_get/src/client/models/gif.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/giphy_get-3.0.4/lib/src/client/models/gif.dart').
    if (_collection!.data!.isNotEmpty && mounted) {
                     ^
../../../../.pub-cache/hosted/pub.dartlang.org/giphy_get-3.0.4/lib/src/views/tab/giphy_tab_detail.dart:240:35: Warning: Operand of null-aware operation '!' has type 'List<GiphyGif>' which excludes null.
 - 'List' is from 'dart:core'.
 - 'GiphyGif' is from 'package:giphy_get/src/client/models/gif.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/giphy_get-3.0.4/lib/src/client/models/gif.dart').
        _list.addAll(_collection!.data!);

**Comment by rlee1990** [comment]
I got the same issue.

**Comment by armandojimenez** [comment]
Same issue here...

**Comment by bazookon** [comment]
WIP

**Comment by bazookon** [comment]
Can you post your flutter doctor please @rlee1990 @mashegoindustries

**Comment by pburel** [comment]
Raygun found:
Message: Null check operator used on a null value
_GiphyTabDetailState._loadMore in package:giphy_get/src/views/tab/giphy_tab_detail.dart:213
_GiphyTabDetailState._scrollListener in package:giphy_get/src/views/tab/giphy_tab_detail.dart:251

**Comment by rlee1990** [comment]
@bazookon was this fixed with the newest update?

**Comment by pburel** [comment]
sorry no.

_AssertionError._doThrowNew in dart:core-patch/errors_patch.dart:51
_AssertionError._throwNew in dart:core-patch/errors_patch.dart:40
ScrollController.position in package:flutter/src/widgets/scroll_controller.dart:108
_DraggableScrollableSheetScrollController.position in package:flutter/src/widgets/draggable_scrollable_sheet.dart:725
_GiphyTabDetailState._scrollListener in package:giphy_get/src/views/tab/giphy_tab_detail.dart:685
ChangeNotifier.notifyListeners in package:flutter/src/foundation/change_notifier.dart:308
ChangeNotifier.notifyListeners in package:flutter/src/foundation/change_notifier.dart:308

════════ Exception caught by foundation library ════════════════════════════════
ScrollController attached to multiple scroll views.
'package:flutter[/src/widgets/scroll_controller.dart]()':
package:flutter/…/widgets/scroll_controller.dart:1
Failed assertion: line 108 pos 12: '_positions.length == 1'

════════════════════════════════════════════════════════════════════════════════

**Comment by pburel** [comment]
_GiphyTabDetailState._scrollListener in package:giphy_get/src/views/tab/giphy_tab_detail.dart:250
correcting with 'positions.**last**' ..... if ((widget.scrollController.positions.last.extentAfter

**Comment by bazookon** [comment]
@pburel thank
