### ISSUE TITLE
flutter 3.0 Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by phantran** [bazookon/giphy_get#28]

**Comment by tjcampanella** [comment]
Can you please update the package for flutter 3?

**Comment by hifiaz** [comment]
fix on [this](https://github.com/bazookon/giphy_get/pull/30) let's wait for new version

**Comment by bazookon** [comment]
Fixed, thans @hifiaz 👏
