### ISSUE TITLE
Is there a way to use it with SafeArea?

### ISSUE THREAD

**Issue by etgkqo** [bazookon/giphy_get#29]
SafeArea is not applied when using GiphyGet.getGif (bottom red box in the picture) How can I apply SafeArea?
![IMG_AB7D210BA465-1](https://user-images.githubusercontent.com/16192326/172303846-dc7ace46-548d-42ac-b4da-c59cef6d7422.jpeg)

**Comment by bazookon** [comment]
WIP

**Comment by bazookon** [comment]
Thanks @etgkqo  fixed in version 3.1.0!
