### ISSUE TITLE
Add Pull Request #36 to Add Debounce to Searches

### ISSUE THREAD

**Issue by ScottWallace** [bazookon/giphy_get#37]
Currently, search queries are executing with each keystroke. Added an optional parameter to `GiphyGet.getGif` called `debounceTimeInMilliseconds` defaulting to 350 milliseconds.

My search results were coming out strange. When I type "cabin", I get the results for the letter "C" for a while.  Eventually it gives proper results for the chosen query, but the user is confused by the earlier partial queries.

Also, theoretically, it should make search results seem faster, as it's not doing the full work with each keystroke.

I have included a `Debounce` class that is self-disposing, and placed it in `/lib/src/tools`. I have also updated the documentation to reflect the change.

https://github.com/bazookon/giphy_get/pull/36

**Comment by ScottWallace** [comment]
This is the needed solution to https://github.com/bazookon/giphy_get/pull/34. Adding a debounce at a higher level allows the user to control via parameter the debounce time.

**Comment by simplenotezy** [comment]
+1 - will also give improved performance
