### ISSUE TITLE
Depnedency Constraints 

### ISSUE THREAD

**Issue by Yogesh-Dubey-Ayesavi** [bazookon/giphy_get#54]
Can you guys update the dependencies, because in my case version solving is getting failed again and again

**Comment by KayesAshfaQ** [comment]
I'm facing the same issue. 
It's because giphy_get still depends on http 0.13.3

`giphy_get >=2.0.1 depends on http ^0.13.3 and project_name depends on http ^1.1.0, giphy_get >=2.0.1 is forbidden.`

**Comment by Yogesh-Dubey-Ayesavi** [comment]
Any updates?

**Comment by bazookon** [comment]
done!
