### ISSUE TITLE
Allow for more customization

### ISSUE THREAD

**Issue by orevial** [bazookon/giphy_get#55]
Right now giphy_get is great but the look and feel cannot be customized to match the app's brand.

Here is a screenshot with things that might be useful to customize: 

![Capture d’écran 2023-07-20 à 10 54 38](https://github.com/bazookon/giphy_get/assets/5528566/31e95fc7-9b7b-4851-8c90-59db5291ff21)

* Modal handlebar
* Search bar including : 
  * search icon (the icon itself and its color)
  * text style (font, size, color, etc)
  * closing icon (the icon itself and its color)
* GIF previews shapes (e.g. more or less rounded)
* Text or widget "powered by GIPHY". It would be particulary useful to be able to replace this with a custom component to support translation

I know that package [giphy_picker](https://pub.dev/packages/giphy_picker) allows for [more customization](https://github.com/firstfloorsoftware/giphy_picker/blob/master/lib/giphy_picker.dart) (but I can't use it because they don't allow opening the picker in a modal view and opens a new page instead), would it make sense to use the same types of optional builders for each part of the modal to build the modal with customized widgets ? 

I could propose a PR for this, let me know

**Comment by bazookon** [comment]
amazing feel free to pr!
